# 基礎串口與中斷支援
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# GPIO 支援
CONFIG_GPIO=y

# Console 設定 (Disable Standard Consoles to use Custom Protocol Log)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_BACKEND_UART=n

# 強制啟用 Log Output 模組 (因為停用了標準 Backend 但需要用 log_output API)
CONFIG_LOG_OUTPUT=y

# 啟用日誌系統 (非同步模式)
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=2000
CONFIG_LOG_PRINTK=y

CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n

# 啟用 Async UART (DMA)
CONFIG_UART_ASYNC_API=y
CONFIG_NRFX_UARTE=y

# 啟用 SPI FLASH & LITTLEFS 支援
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y

# 指定 LittleFS 放在外部 Flash (需要 pm.yml 中有定義對應的 region)
CONFIG_PM_PARTITION_REGION_LITTLEFS_EXTERNAL=y
# 配置 LittleFS partition size，需小於或等於 pm.yml 中定義的 region 大小 
CONFIG_PM_PARTITION_SIZE_LITTLEFS=0x00600000
CONFIG_FILE_SYSTEM_MKFS=y


# 啟用 BLE 支援
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="TJ3"

CONFIG_SENSOR=y
CONFIG_ATM90E26=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

# 記憶體配置
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
