# Logging
CONFIG_LOG=n
# CONFIG_LOG_MODE_DEFERRED=y
# CONFIG_LOG_BUFFER_SIZE=10240

# Serial
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n

# Disable Console
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SHELL=n

# Logging Output support (required for custom backends using log_output_*)
CONFIG_LOG_OUTPUT=n
